### PR TITLE
feat: canned response for esp32 comm errors

### PR DESCRIPTION
**Pull request by BhendiBoi**

### CODE REVIEW

**Comment by max-bromberg** [comment]
The new ESP32 canned response looks good. According to our helpers, the suggestions in that response apply to all ESP32's, so a commit to generalize the response would be appreciated.

As far as the ask command, we will be moving away from individual commands that have the sole purpose of providing a canned response and integrating them into the tag system. I will be pushing a commit soon to add a new "direct aliases" field. Put simply, direct aliases are aliases for root commands rather than arguments for the tag command. With this understanding, a commit to move the ask command's response into a tag file would also be greatly appreciated.

Thanks for your contributions!

**Comment by BhendiBoi** [comment]
@BluLightShow thanks for the response! I will definitely move the !ask command into a tag file. however, the ESP32 CAM is the only board where GPIO0 and GND have to be shorted, I can still generalize it to a great extent, however. I will work on it now, thanks :)

**Comment by BhendiBoi** [comment]
@BluLightShow there, all done! please tell me what else I can do for the bot/server :smile: Also, do you mind if I add another canned response in the same pr?

**Comment by max-bromberg** [comment]
> @BluLightShow there, all done! please tell me what else I can do for the bot/server 😄 Also, do you mind if I add another canned response in the same pr?

Go right ahead :)

**Comment by BhendiBoi** [comment]
@BluLightShow hello! i was told by @tas_dogu that you did not really like the idea of !ask, should i remove it? i made it only because of the suggestion made by @frozenrat a while ago

**Comment by max-bromberg** [comment]
> @BluLightShow hello! i was told by @tas_dogu that you did not really like the idea of !ask, should i remove it? i made it only because of the suggestion made by @frozenrat a while ago

Idea is all good, only issue was what I mentioned before in that we're moving away from individual commands for canned responses. This pull request will be merged soon.

**Pull request merged**
