### PR TITLE
add: pullup tag

### PR DESCRIPTION
**Pull request by AnonEngineering**

### CODE REVIEW

**Comment by AnonEngineering** [comment]
Added pullup.json. Not at all sure about this process, please forgive gross breaches of protocol!

**Comment by max-bromberg** [comment]
Mostly good on the process! I've gone ahead and added a commit to this PR that adds some generic names for each field you included in the tag. Feel free to change these names or change the format of the entire tag, but discord embeds require fields to have both a name and a value. I would suggest merging the one sentence per field into some more generalized field categories, maybe only one or two fields with what's written down, it will already appear large with the image. Thanks for contributing!

**Comment by max-bromberg** [comment]
Looks good!

**Comment by max-bromberg** [comment]
Merged to wrong branch. Will fix later today.

**Comment by AnonEngineering** [comment]
Maybe I am getting the "gist" of this :) Thanks!

**Pull request merged**
