### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by prakulkhebbur**
Blue pls consider automatic replay saves a lot of time for waiting people who need to call the command... if u wish u can change and the codeblock command now works.

### CODE REVIEW

**Comment by prakulkhebbur** [comment]
?

**Comment by max-bromberg** [comment]
Canned responses will not be individual commands, but unified to a single file with all responses.

**Comment by prakulkhebbur** [comment]
Ok at least update the code block command

**Comment by prakulkhebbur** [comment]
@BluLightShow

**Comment by max-bromberg** [comment]
See 66c48af8fec28a60ab574e96e7cbbe24209f1ebf

**Pull request closed without merging**
